### ISSUE TITLE
Portal issues with React v16

### ISSUE THREAD

**Issue by amertak** [pradel/react-minimalist-portal#10]
As stated in https://github.com/facebook/react/pull/8386 and also tested with alpha versions, this library is not working with new React Core.

Putting it here as https://github.com/facebook/react/pull/8386 gives a solution :)
Will definitely work on pull request to make this library work with old and new React core.

**Comment by pradel** [comment]
That could be really cool thanks!

**Comment by amertak** [comment]
https://github.com/pradel/react-minimalist-portal/pull/11

Basic idea, its working for old and new react.

**Comment by pradel** [comment]
Published as 2.0.0
