### ISSUE TITLE
Add possibility to customize the container

### ISSUE THREAD

**Issue by devlato** [pradel/react-minimalist-portal#13]
Hello,

could you add a `node` prop to pass the container from the outside please?

**Comment by pradel** [comment]
Sorry I don't understand, what do you mean?

**Comment by devlato** [comment]
I mean, currently you just create a `div` inside a body and render everything there. Could you add a prop so user could pass a specific node instead of `document.body`? And a prop that allow not to add `div`?

**Comment by pradel** [comment]
Oh okay I got it I will do that on the next version :)

**Comment by devlato** [comment]
@pradel Thanks! :grin:

**Comment by AnnKolesnicova** [comment]
How's the progress?

**Comment by pradel** [comment]
I don't have the time right now, but I would be happy to accept a pull request for that :)

**Comment by pradel** [comment]
Released as v2.3.0 🎉
